### ISSUE TITLE
OSCAR PDR request from GITC

### ISSUE THREAD

**Issue by viviant100** [podaac/SOTO#16]
Jerome (GITC) asked David C. to add some OSCAR imagery for GITC to test with in gibs2/PDR.

**Comment by viviant100** [comment]
Jerome (GITC) asked David C. to add some OSCAR imagery for GITC to test with in gibs2/PDR.

**Comment by frankinspace** [comment]
@davidcolemanjpl finished sending oscar imagery to gitc. Closing this as complete
