### ISSUE TITLE
Update SWORD to v16

### ISSUE THREAD

**Issue by frankinspace** [podaac/SOTO#27]
Need to update the FTS database to use the latest V16 SWORD data.

Shape files can be downloaded from http://gaia.geosci.unc.edu/SWORD/SWORD_v16_shp.zip

**Comment by frankinspace** [comment]
Blocked by #28

**Comment by frankinspace** [comment]
Tested in UAT with Postman.

Results:

[FTS.postman_test_run.json](https://github.com/podaac/SOTO/files/14984708/FTS.postman_test_run.json)

**Comment by frankinspace** [comment]
Go for OPS. Received concurrence in slack from @cassienickles

**Comment by ymchenjpl** [comment]
The SWORD v16 FTS database has been loaded into the Services OPS venue by Tim and Max on 4/16/24.  See bottom of OPS wiki page at: https://wiki.jpl.nasa.gov/display/PD/FTS+v0.2.0+OPS+Services+Deployment+Procedure+-+04-29-21%2C+4-15-24

**Comment by frankinspace** [comment]
Thank you @ymchenjpl !

I've run the same tests against OPS and everything has passed. Going to closing out this ticket.
[OPS-FTS.postman_test_run.json](https://github.com/podaac/SOTO/files/15030688/OPS-FTS.postman_test_run.json)
