### ISSUE TITLE
Create outline for the new story

### ISSUE THREAD

**Issue by frankinspace** [podaac/SOTO#8]
The outline would just be a list of steps that walk through the story where each step in the story has at a minimum:
 
SOTO URL to display
Markdown formatted text to display during that step

**Comment by NickTarpinian** [comment]
[SOTO_Tour_Story_1.zip](https://github.com/podaac/SOTO/files/13384515/SOTO_Tour_Story_1.zip)

Attached is the outline and thumbnail PNG for the first SOTO tour story.

**Comment by NickTarpinian** [comment]
[SOTO_Tour_Story_1.docx](https://github.com/user-attachments/files/17804233/SOTO_Tour_Story_1.docx)

Added an additional section on La Nina.
